Repository CodeFantasia/iOS, pull requests merged in 2023-11, with the labels that each got.

#87 [로그인, 회원가입] 유효성 검사 UI 구현 완료
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Assets.xcassets/Authentication/default_profile.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/default_profile.imageset/default_profile.png
  CodeFantasia/Assets.xcassets/Authentication/default_profile.imageset/default_profile@2x.png
  CodeFantasia/Assets.xcassets/Authentication/default_profile.imageset/default_profile@3x.png
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Extension/UIView+.swift
Labels: UI

#88 [새 글 작성 페이지] 새 글 작성 페이지 모달형식으로 변경, 입력폼 덜 작성했을 시 경고창 생성, 뒤로가기버튼 추가, 플랫…
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/Controller/NewPost/PlatformSelectionViewController.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/Resource/Utilities.swift
Labels: UI

#89 [FEAT] 프로필 페이지 로그인된 유저 정보 불러오기
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/TabbarM.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement, UI

#90 Feat/031 search page filter
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/ProjectBoard/FilterBottomSheetVC.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectBoard/ProjectSearchViewVC.swift
  CodeFantasia/TabbarM.swift
Labels: enhancement

#91 [Feat] 내 프로젝트 페이지 데이터 없을때 보여줄 화면 구성
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: UI

#93 자동완성 기능 -완-
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/DataModel.swift
Labels: enhancement

#100 [FEAT] 프로젝트 상세 페이지 어느 화면에서 들어가냐에따라 요소 변경
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
  CodeFantasia/Resource/Images.swift
Labels: UI

#101 [새 글 작성 페이지] 데이터 모델 업데이트(프로젝트: 유저아이디)
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/DataModel.swift
Labels: Setting

#103 [FEAT] 유저아이디와 프로젝트 배열 내 writerID 일치하는지 확인하여 UI 변환
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
Labels: enhancement

#109 Cf 041 project detail edit button
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement

#110 Feature/cf 039 project detail func
  CodeFantasia/MyProject/MyProjectTableViewCell.swift
  CodeFantasia/MyProject/MyProjectViewModel.swift
  CodeFantasia/TabbarM.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement

#111 Feat: "검색 페이지 셀 탭 시 상세페이지로 이동"
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/MoreDefault.imageset/Contents.json
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/MoreDefault.imageset/MoreButton.png
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/MoreDefault.imageset/MoreButton@2x.png
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/MoreDefault.imageset/MoreButton@3x.png
  CodeFantasia/ProjectBoard/ProjectBoardTableviewCell.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectBoard/ProjectSearchViewVC.swift
Labels: enhancement

#114 [유저 정보 입력] UI 완성 및 Firebase 연결 완료
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/Authentication/DropdownTableView.swift
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/Extension/UIViewController+.swift
  CodeFantasia/Feature/AuthManager.swift
  CodeFantasia/Feature/ImageStorageManager.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Repository/UserRepository.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement, UI, Setting

#116 [FEAT] 프로필 수정 페이지 연결 및 데이터 구현
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
  CodeFantasia/Repository/UserRepository.swift
Labels: enhancement

#117 [상세페이지] 신고버튼 기능 구현
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/Feature/NewPageManager.swift
  CodeFantasia/MyProject/MyProjectViewModel.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
  CodeFantasia/Repository/ProjectRepository.swift
Labels: enhancement

#119 [새 글 작성 페이지] 썸네일이미지업로드
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
Labels: enhancement

#121 Design: "UI 변경"
  CodeFantasia/ProjectBoard/ProjectBoardTableviewCell.swift
Labels: enhancement

#122 [이용약관동의] 회원가입 화면에 구현
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/SignUp/TermsOfConditionsController.swift
  CodeFantasia/Controller/Authentication/SignUp/TermsOfConditionsView.swift
Labels: enhancement, Setting

#124 [새 글 작성 페이지] 수정페이지 자료이동 및 오류 해결
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/DataModel.swift
Labels: bug, enhancement

#128 회원가입 단계에서 회원탈퇴 버튼 숨김 처리
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
Labels: Setting

#129 Feat: "키보드 나오면 위로 스크롤 가능"
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Extension/UIViewController+.swift
Labels: enhancement

#130 [앱 아이콘] 앱 아이콘 추가
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/Contents.json
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/Pla (3) 1 (1).png
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/Screenshot 2023-10-27 at 3.02.05 AM.png
Labels: enhancement

#135 [FEAT] 프로필 등록 및 수정 페이지 여러가지 수정, 새글작성 페이지 수정하기시 글복사 해결
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
  CodeFantasia/Repository/ProjectRepository.swift
  CodeFantasia/Resource/Images.swift
Labels: enhancement, UI

#138 [FEAT] 프로젝트 디테일 페이지 사용자 로고 탭시 작성자 프로필 보여주기
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
Labels: enhancement, UI

#141 Feat: "나의 프로젝트 새로고침 구현"
  CodeFantasia/MyProject/MyProjectViewModel.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement

#142 Update README.md
  README.md
Labels: documentation

#145 Design: " 테이블 셀 디자인 변경"
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/CODECOCOON.png
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/Contents.json
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/Pla (3) 1 (1).png
  CodeFantasia/Assets.xcassets/AppIcon_long.imageset/CODE COCOON-3 1.jpeg
  CodeFantasia/Assets.xcassets/AppIcon_long.imageset/CODE COCOON-3 2.jpeg
  CodeFantasia/Assets.xcassets/AppIcon_long.imageset/CODE COCOON-3.jpeg
  CodeFantasia/Assets.xcassets/AppIcon_long.imageset/Contents.json
  CodeFantasia/ProjectBoard/ProjectBoardTableviewCell.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectBoard/ProjectSearchViewVC.swift
Labels: enhancement

#150 [UI] 로그인, 회원가입, 프로필 정보 기입 페이지 UI 수정
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/Contents.json
  CodeFantasia/Assets.xcassets/AppIcon.appiconset/cocoon-1.png
  CodeFantasia/Assets.xcassets/AppLogo.imageset/CODE COCOON-3-1 1.png
  CodeFantasia/Assets.xcassets/AppLogo.imageset/CODE COCOON-3-1 2.png
  CodeFantasia/Assets.xcassets/AppLogo.imageset/CODE COCOON-3-1.png
  CodeFantasia/Assets.xcassets/AppLogo.imageset/Contents.json
  CodeFantasia/Assets.xcassets/LaunchScreen.imageset/Contents.json
  CodeFantasia/Assets.xcassets/LaunchScreen.imageset/cocoon 1.png
  CodeFantasia/Assets.xcassets/LaunchScreen.imageset/cocoon 2.png
  CodeFantasia/Assets.xcassets/LaunchScreen.imageset/cocoon.png
  CodeFantasia/Controller/Authentication/LogIn/LoginController.swift
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/CustomUI/Utilities.swift
  CodeFantasia/Resource/Metrics.swift
Labels: UI

#151 [Design] UI 수정 및 일부 기능 변경
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/MyProject/MyProjectTableViewCell.swift
  CodeFantasia/MyProject/MyProjectViewModel.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/ProjectDetailNoticeBoard/PaddingLabel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/Repository/UserRepository.swift
  CodeFantasia/Resource/Palette.swift
  CodeFantasia/SceneDelegate.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: UI

#152 [새 글 작성 페이지] 썸네일 이미지뷰 디폴트 아이콘 추가, 작성 및 수정완료 버튼누르면 게시판 데이터 갱신
  CodeFantasia/Assets.xcassets/Authentication/AppIcon.appiconset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/Symbol.symbolset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-30.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 1.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 2.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 3.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 4.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 5.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-60.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-90.png
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
Labels: enhancement, UI

#154 [회원가입] 이메일 중복 방지
  CodeFantasia/Controller/Authentication/LogIn/LoginController.swift
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/CustomUI/Utilities.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/Feature/AuthManager.swift
Labels: enhancement

#157 [새 글 작성 페이지] 썸넬이미지뷰 수정, 프로젝트 소개 텍스트뷰 키보드 수정
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-30.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 1.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 2.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 3.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 4.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50 5.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-50.png
  CodeFantasia/Assets.xcassets/Authentication/default.imageset/icons8-을-더한-60.png
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
Labels: bug, UI

#159 feat: 회원 탈퇴 시 이메일 지우는 기능 구현
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/Feature/AuthManager.swift
Labels: bug

#164 feat: 중복이메일 확인 버그 수정
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
Labels: bug

#153 [FIX] 프로젝트 소개 및 프로필 나의 소개 길게 작성시 화면 밖으로 텍스트 넘어가는 현상 해결
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/MyProject/MyProjectTableViewCell.swift
  CodeFantasia/Profile/ProfileViewController.swift
Labels: bug

#166 로그인, 회원가입 자잘한 버그 수정
  CodeFantasia/Assets.xcassets/Authentication/CheckBox.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/CheckBox.imageset/check-mark 1.png
  CodeFantasia/Assets.xcassets/Authentication/CheckBox.imageset/check-mark 2.png
  CodeFantasia/Assets.xcassets/Authentication/CheckBox.imageset/check-mark.png
  CodeFantasia/Assets.xcassets/Authentication/EmptyBox.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Authentication/EmptyBox.imageset/empty 1.png
  CodeFantasia/Assets.xcassets/Authentication/EmptyBox.imageset/empty 2.png
  CodeFantasia/Assets.xcassets/Authentication/EmptyBox.imageset/empty.png
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/SignUp/TermsOfConditionsView.swift
Labels: bug

#168 [Fix] 실시간 데이터 베이스 업로드 오류 수정 및 이미 삭제된 게시글 클릭했을때의 처리
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/Feature/AuthManager.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
Labels: bug

#169 [새 글 작성 페이지] 작성완료 버튼탭 수정
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
Labels: bug

#171 Cf 066 new page text field tool bar
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
Labels: enhancement

#179 feat: 이용약관 및 개인정보 처리 방침 수정
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Extension/WKWebView+.swift
Labels: enhancement

#180 [FEAT] 신고 메세지 변경, 프로필 수정 드롭다운 오류 해결, 프로젝트 게시판 데이터 변경시 화면 업데이트
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/Resource/Images.swift
Labels: bug, enhancement, UI

#184 Feature/기간지나면 모집 중으로 변경
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/NewPost/AutoCompleteManager.swift
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/ProjectBoard/FilterBottomSheetVC.swift
  CodeFantasia/ProjectBoard/ProjectBoardTableviewCell.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
Labels: enhancement

#182 Update README.md
  README.md
Labels: documentation

#186 [새 글 작성 페이지] 제목 텍스트필드 키보드 수정
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
Labels: bug

#187 [FEAT] 팔로우 기능 완성
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/AppDelegate.swift
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/Feature/FirebaseManager.swift
  CodeFantasia/Profile/FollowTableVC.swift
  CodeFantasia/Profile/FollowViewCell.swift
  CodeFantasia/Profile/FollowViewModel.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
  CodeFantasia/Repository/ProjectRepository.swift
  CodeFantasia/Repository/UserRepository.swift
Labels: enhancement, UI

#189 새 글 작성 UI 수정
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Assets.xcassets/AddPhoto.imageset/AddPhoto 1.png
  CodeFantasia/Assets.xcassets/AddPhoto.imageset/AddPhoto 2.png
  CodeFantasia/Assets.xcassets/AddPhoto.imageset/AddPhoto.png
  CodeFantasia/Assets.xcassets/AddPhoto.imageset/Contents.json
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/Controller/NewPost/NewpostUtilities.swift
  CodeFantasia/CustomUI/TextView.swift
  CodeFantasia/Extension/UITextField+.swift
  CodeFantasia/Extension/UIView+.swift
  CodeFantasia/Resource/Fonts.swift
  CodeFantasia/Resource/Metrics.swift
Labels: enhancement, UI

#190 [Design] 프로필 페이지UI 일부 수정
  CodeFantasia/Profile/FollowTableVC.swift
  CodeFantasia/Profile/FollowViewModel.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
Labels: UI

#191 Feature/cf 074 overall UI fix
  CodeFantasia/Assets.xcassets/Image.imageset/Contents.json
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Controller/Authentication/UserDataManageController.swift
  CodeFantasia/Controller/NewPost/NewPageViewController.swift
  CodeFantasia/Controller/NewPost/NewpostUtilities.swift
  CodeFantasia/CustomUI/Utilities.swift
  CodeFantasia/Resource/Metrics.swift
  CodeFantasia/Resource/Palette.swift
Labels: enhancement, UI
