Repository CodeFantasia/iOS, pull requests merged in 2023-10, with the labels that each got.

#12 Feature/cf 004 tabbar UI created
  .DS_Store
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeFantasia/AppDelegate.swift
  CodeFantasia/Assets.xcassets/Tabbar/Contents.json
  CodeFantasia/Assets.xcassets/Tabbar/TabbarHome.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Tabbar/TabbarHome.imageset/TabbarHome 1.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarHome.imageset/TabbarHome 2.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarHome.imageset/TabbarHome.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarMyProject.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Tabbar/TabbarMyProject.imageset/Image 1.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarMyProject.imageset/Image 2.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarMyProject.imageset/Image 3.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarProfile.imageset/Contents.json
  CodeFantasia/Assets.xcassets/Tabbar/TabbarProfile.imageset/Image 2.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarProfile.imageset/Image 3.png
  CodeFantasia/Assets.xcassets/Tabbar/TabbarProfile.imageset/Image 4.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/Contents.json
  CodeFantasia/Assets.xcassets/TableCellMockUp/Python.imageset/Contents.json
  CodeFantasia/Assets.xcassets/TableCellMockUp/Python.imageset/Image.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/Python.imageset/Image@2x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/Python.imageset/Image@3x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/digimon.imageset/Contents.json
  CodeFantasia/Assets.xcassets/TableCellMockUp/digimon.imageset/digimon.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/digimon.imageset/digimon@2x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/digimon.imageset/digimon@3x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/javascript.imageset/Contents.json
  CodeFantasia/Assets.xcassets/TableCellMockUp/javascript.imageset/Image 2.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/javascript.imageset/Image 2@2x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/javascript.imageset/Image 2@3x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/pokemon.imageset/Contents.json
  CodeFantasia/Assets.xcassets/TableCellMockUp/pokemon.imageset/pokemon.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/pokemon.imageset/pokemon@2x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/pokemon.imageset/pokemon@3x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/swift.imageset/Contents.json
  CodeFantasia/Assets.xcassets/TableCellMockUp/swift.imageset/Image 1.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/swift.imageset/Image 1@2x.png
  CodeFantasia/Assets.xcassets/TableCellMockUp/swift.imageset/Image 1@3x.png
  CodeFantasia/MyProjectVC.swift
  CodeFantasia/ProfileVC.swift
  CodeFantasia/ProjectBoardTableviewCell.swift
  CodeFantasia/ProjectBoardVC.swift
  CodeFantasia/SceneDelegate.swift
  CodeFantasia/TabbarM.swift
Labels: UI

#13 [프로젝트 게시판 디테일] UI 작성
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeFantasia/ProjectDetailNoticeBoard/PaddingLabel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/Resource/Fonts.swift
  CodeFantasia/Resource/Images.swift
  CodeFantasia/Resource/Metrics.swift
  CodeFantasia/Resource/Palette.swift
Labels: UI

#14 [feat]: 새 글 작성 UI 생성
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/NewPageViewController.swift
Labels: UI

#16 [내 프로젝트 페이지] UI 작성
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/MyProject/MyProjectTableViewCell.swift
  CodeFantasia/MyProject/MyProjectVC.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Resource/CustomAlert.swift
Labels: UI

#18 [템플릿] 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: Setting

#20 [템플릿] PR 템플릿 추가
  .github/pull_request_template.md
Labels: Setting

#22 [프로젝트 게시판 디테일] 디폴트 UI 및 버튼 효과 부여
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Extension/Date+Format.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/UIHoverButton.swift
  CodeFantasia/Resource/Images.swift
  CodeFantasia/Resource/Metrics.swift
Labels: enhancement, UI

#21 [로그인, 회원가입, 회원 정보 추가] UI 작성
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Assets.xcassets/AppleSignUp.imageset/Contents.json
  CodeFantasia/Assets.xcassets/AppleSignUp.imageset/apple-signinbutton-560-removebg-preview 1.png
  CodeFantasia/Assets.xcassets/AppleSignUp.imageset/apple-signinbutton-560-removebg-preview 2.png
  CodeFantasia/Assets.xcassets/AppleSignUp.imageset/apple-signinbutton-560-removebg-preview.png
  CodeFantasia/LogIn/LoginVC.swift
  CodeFantasia/Resource/Button.swift
  CodeFantasia/Resource/Label.swift
  CodeFantasia/Resource/Metrics.swift
  CodeFantasia/Resource/TextField.swift
  CodeFantasia/SignUp/TermsOfConditionsVC.swift
  CodeFantasia/SignUp/UserInfoInputVC.swift
Labels: UI

#30 [프로필, 내 프로젝트] 레이아웃 제약 조건 수정, 코드 간결화 및 UI 일부 수정
  CodeFantasia/MyProject/MyProjectTableViewCell.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: UI

#33 [Firebase] 파이어베이스 매니저 및 세팅
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeFantasia.xcodeproj/xcshareddata/xcschemes/CodeFantasia - Dev.xcscheme
  CodeFantasia.xcodeproj/xcshareddata/xcschemes/CodeFantasia.xcscheme
  CodeFantasia/AppDelegate.swift
  CodeFantasia/Feature/FirebaseManager.swift
  CodeFantasia/GoogleService-Info-Dev.plist
  CodeFantasia/GoogleService-Info.plist
  CodeFantasia/Info-Dev.plist
Labels: enhancement, Setting

#38 [Firebase] 프로젝트 데이터 불러오는 기능 추가
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/DataModel.swift
  CodeFantasia/Extension/Data+.swift
  CodeFantasia/Feature/FirebaseManager.swift
  CodeFantasia/Repository/ProjectRepository.swift
Labels: enhancement

#41 fix: 경로 삭제된 폴더 추가
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/.DS_Store
Labels: bug

#43 [프로젝트 게시판 디테일] 프로젝트 정보 가져오기 및 신고, 편집, 이미지 버튼 세팅
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Extension/Rx+UIViewController.swift
  CodeFantasia/Extension/UIImageView+.swift
  CodeFantasia/Extension/UIViewController+.swift
  CodeFantasia/ProjectDetailNoticeBoard/PaddingLabel.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewController.swift
  CodeFantasia/ProjectDetailNoticeBoard/ProjectDetailNoticeBoardViewModel.swift
  CodeFantasia/Resource/Images.swift
Labels: enhancement

#53 [Gitignore 파일 수정] .DS_Store 전부 삭제 및 gitignore 파일에 추가
  .DS_Store
  .gitignore
  CodeFantasia/.DS_Store
  CodeFantasia/Extension/.DS_Store
Labels: bug

#50 파이어스토어 데이터 불러와 프로필 및 내 프로젝트 화면에 적용
  .DS_Store
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/MyProject/MyProjectViewModel.swift
  CodeFantasia/Profile/ProfileViewController.swift
  CodeFantasia/Profile/ProfileViewModel.swift
  CodeFantasia/Repository/UserRepository.swift
  CodeFantasia/TabbarM.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement

#56 fix: .DS_Store git cache 에서 삭제
  .DS_Store
Labels: bug

#61 [새 글 작성 페이지] 출시플랫폼 자료형식 수정
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/NewPageViewController.swift
Labels: bug

#62 feat. 내 프로젝트 페이지의 셀 탭할 경우 프로젝트 디테일 페이지로 이동 구현
  CodeFantasia/MyProject/MyProjectViewModel.swift
  CodeFantasia/TabbarM.swift
  CodeFantasia/To be deleted/MyProjectVC.swift
Labels: enhancement

#63 [새 글 작성 페이지] project 데이터 모델 "연락방법" 추가
  CodeFantasia/DataModel.swift
  CodeFantasia/NewPageViewController.swift
Labels: enhancement

#68 [회원가입/로그인] 파이어베이스 연결
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/Authentication/LogIn/LoginController.swift
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/DataModel.swift
  CodeFantasia/Extension/UIViewController+.swift
  CodeFantasia/Feature/UserManager.swift
  CodeFantasia/GoogleService-Info-Dev.plist
Labels: enhancement, Setting

#67 Fix: "이미지가 나타나지 않는 에러 수정"
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/ProjectBoard/ProjectBoardTableviewCell.swift
  CodeFantasia/ProjectBoard/ProjectBoardVC.swift
  CodeFantasia/ProjectBoard/ProjectSearchViewVC.swift
Labels: bug

#71 [AuthManager] FirebaseAuth 추가
  CodeFantasia/Feature/UserManager.swift
Labels: bug

#73 [로그인/회원가입] 로그인, 회원가입 후 Controller 연결
  CodeFantasia.xcodeproj/project.pbxproj
  CodeFantasia/Controller/Authentication/LogIn/LoginController.swift
  CodeFantasia/Controller/Authentication/SignUp/RegistrationController.swift
  CodeFantasia/Feature/AuthManager.swift
  CodeFantasia/SceneDelegate.swift
  CodeFantasia/TabbarM.swift
Labels: enhancement, Setting

#72 [FEAT] 로그아웃 기능 구현
  CodeFantasia/Profile/ProfileViewController.swift
Labels: enhancement

#84 Feat: "모집 분야 디폴트 아이콘 추가"
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/SkillDefault.imageset/Contents.json
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/SkillDefault.imageset/New Piskel 1.png
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/SkillDefault.imageset/New Piskel 2.png
  CodeFantasia/Assets.xcassets/ProjectBoardTableCell/SkillDefault.imageset/New Piskel.png
Labels: UI
